[package]
name = "web_scraper"
version = "0.1.0"


[dependencies]

reqwest = {version = "0.11", features = ["blocking"]}
scraper = "0.13.0"
csv = "1.1"
table-extract ="0.2.2"
serde = { version = "1", features = ["derive"] }
select = "0.5.0"


